/**
 *	Map Styles
 *
 *	Free styles available at http://snazzymaps.com/
 */

var mapStyles =[{"featureType":"water","elementType":"all","stylers":[{"hue":"#e9ebed"},{"saturation":-78},{"lightness":67},{"visibility":"simplified"}]},{"featureType":"landscape","elementType":"all","stylers":[{"hue":"#ffffff"},{"saturation":-100},{"lightness":100},{"visibility":"simplified"}]},{"featureType":"road","elementType":"geometry","stylers":[{"hue":"#bbc0c4"},{"saturation":-93},{"lightness":31},{"visibility":"simplified"}]},{"featureType":"poi","elementType":"all","stylers":[{"hue":"#ffffff"},{"saturation":-100},{"lightness":100},{"visibility":"off"}]},{"featureType":"road.local","elementType":"geometry","stylers":[{"hue":"#e9ebed"},{"saturation":-90},{"lightness":-8},{"visibility":"simplified"}]},{"featureType":"transit","elementType":"all","stylers":[{"hue":"#e9ebed"},{"saturation":10},{"lightness":69},{"visibility":"on"}]},{"featureType":"administrative.locality","elementType":"all","stylers":[{"hue":"#2c2e33"},{"saturation":7},{"lightness":19},{"visibility":"on"}]},{"featureType":"road","elementType":"labels","stylers":[{"hue":"#bbc0c4"},{"saturation":-93},{"lightness":31},{"visibility":"on"}]},{"featureType":"road.arterial","elementType":"labels","stylers":[{"hue":"#bbc0c4"},{"saturation":-93},{"lightness":-2},{"visibility":"simplified"}]}]; // light monochrome [http://snazzymaps.com/style/29/light-monochrome]

/* [{"featureType":"administrative","stylers":[{"visibility":"off"}]},{"featureType":"poi","stylers":[{"visibility":"simplified"}]},{"featureType":"road","elementType":"labels","stylers":[{"visibility":"simplified"}]},{"featureType":"water","stylers":[{"visibility":"simplified"}]},{"featureType":"transit","stylers":[{"visibility":"simplified"}]},{"featureType":"landscape","stylers":[{"visibility":"simplified"}]},{"featureType":"road.highway","stylers":[{"visibility":"off"}]},{"featureType":"road.local","stylers":[{"visibility":"on"}]},{"featureType":"road.highway","elementType":"geometry","stylers":[{"visibility":"on"}]},{"featureType":"water","stylers":[{"color":"#abbaa4"}]},{"featureType":"transit.line","elementType":"geometry","stylers":[{"color":"#3f518c"}]},{"featureType":"road.highway","stylers":[{"color":"#ad9b8d"}]}]; // old timey */
/* [{"featureType": "water","stylers": [{ "color": "#000000" }]},{"featureType": "road.highway","elementType": "geometry","stylers": [{ "color": "#2c2c2c" },{ "visibility": "simplified" }]},{"featureType": "road.arterial","elementType": "geometry","stylers": [{ "color": "#555555" }]},{"featureType": "road.local","elementType": "geometry","stylers": [{ "color": "#777777" }]},{"featureType": "poi","stylers": [{ "visibility": "off" }]},{"featureType": "landscape.man_made","elementType": "geometry","stylers": [{ "color": "#111111" }]},{"featureType": "landscape.natural","stylers": [{ "color": "#111111" }]},{"featureType": "road.highway","elementType": "labels.text","stylers": [{ "visibility": "off" }]},{"featureType": "road","elementType": "labels.text.fill","stylers": [{ "color": "#ffffff" }]},{"featureType": "road.highway","elementType": "labels.text.fill","stylers": [{ "visibility": "on" },{ "color": "#aaaaaa" }]},{"featureType": "road.arterial","elementType": "labels.text.fill","stylers": [{ "color": "#aaaaaa" }]},{"featureType": "road.local","elementType": "labels.text.fill","stylers": [{ "color": "#aaaaaa" },{ "visibility": "on" }]},{"featureType": "road.arterial","elementType": "labels.text.stroke","stylers": [{ "visibility": "off" }]},{"featureType": "administrative","elementType": "labels","stylers": [{ "visibility": "off" }]},{"featureType": "road.arterial","elementType": "labels.text.stroke","stylers": [{ "visibility": "on" },{ "color": "#000000" }]},{"featureType": "road.local","elementType": "labels.text","stylers": [{ "color": "#000000" }]},{"featureType": "road.local","elementType": "labels.text.fill","stylers": [{ "color": "#aaaaaa" }]},{"featureType": "road.local","elementType": "geometry","stylers": [{ "color": "#000000" }]},{"featureType": "road.arterial","elementType": "geometry","stylers": [{ "color": "#000000" }]},{"featureType": "road.highway","elementType": "geometry","stylers": [{ "color": "#000000" }]},{"featureType": "road","elementType": "labels","stylers": [{ "visibility": "off" }]},{"featureType": "landscape","elementType": "geometry","stylers": [{ "color": "#333333" }]},{"featureType": "transit","elementType": "labels","stylers": [{ "visibility": "off" }]},{"featureType": "transit","elementType": "geometry","stylers": [{ "color": "#222222" }]},{"featureType": "administrative.country","elementType": "geometry","stylers": [{ "visibility": "on" },{ "color": "#444444" }]},{"featureType": "administrative","elementType": "geometry.fill","stylers": [{ "visibility": "simplified" },{ "color": "#333333" }]},{}]; // original dark */